from .assembly.ShiftParameterMixup import ShiftParameterMixup

from .attributes.ConstantPragma import ConstantPragma
from .attributes.IncorrectSolc import IncorrectSolc
from .attributes.LockedEther import LockedEther
from .attributes.ConstFunctionsAsm import ConstantFunctionsAsm
from .attributes.ConstFunctionsState import ConstantFunctionsState
from .attributes.UnimplementedInterface import MissingInheritance

from .compiler_bugs.storage_signed_integer_array import StorageSignedIntegerArray
from .compiler_bugs.uninitialized_function_ptr_in_constructor import UninitializedFunctionPtrsConstructor
from .compiler_bugs.storage_ABIEncoderV2_array import ABIEncoderV2Array
from .compiler_bugs.ArrayByReference import ArrayByReference
from .compiler_bugs.EnumConversion import EnumConversion
from .compiler_bugs.MultipleConstructorSchemes import MultipleConstructorSchemes
from .compiler_bugs.PublicMappingNested import PublicMappingNested
from .compiler_bugs.ReusedBaseConstructor import ReusedBaseConstructor

from .erc.erc20.incorrect_erc20_interface import IncorrectERC20InterfaceDetection
from .erc.erc20.arbitrary_send_erc20_no_permit import ArbitrarySendErc20NoPermit
from .erc.erc20.arbitrary_send_erc20_permit import ArbitrarySendErc20Permit
from .erc.erc20.arbitrary_send_erc20 import ArbitrarySendErc20
from .erc.erc721.incorrect_erc721_interface import IncorrectERC721InterfaceDetection
from .erc.erc20.unindexed_event_parameters import UnindexedERC20EventParameters

from .functions.arbitrary_send_eth import ArbitrarySendEth
from .functions.suicidal import Suicidal
from .functions.external_function import ExternalFunction
from .functions.unimplemented import UnimplementedFunctionDetection
from .functions.protected_variable import ProtectedVariables
from .functions.permit_domain_signature_collision import DomainSeparatorCollision
from .functions.codex import Codex
from .functions.cyclomatic_complexity import CyclomaticComplexity
from .functions.modifier import ModifierDefaultDetection
from .functions.dead_code import DeadCode

from .naming_convention.naming_convention import NamingConvention

from .operations.low_level_calls import LowLevelCalls
from .operations.unused_return_values import UnusedReturnValues
from .operations.unchecked_transfer import UncheckedTransfer
from .operations.unchecked_low_level_return_values import UncheckedLowLevel
from .operations.unchecked_send_return_value import UncheckedSend
from .operations.void_constructor import VoidConstructor
from .operations.block_timestamp import Timestamp
from .operations.bad_prng import BadPRNG
from .operations.encode_packed import EncodePackedCollision
from .operations.missing_events_access_control import MissingEventsAccessControl
from .operations.missing_events_arithmetic import MissingEventsArithmetic
from .operations.missing_zero_address_validation import MissingZeroAddressValidation

from .reentrancy.reentrancy_benign import ReentrancyBenign
from .reentrancy.reentrancy_read_before_write import ReentrancyReadBeforeWritten
from .reentrancy.reentrancy_eth import ReentrancyEth
from .reentrancy.reentrancy_no_gas import ReentrancyNoGas
from .reentrancy.reentrancy_events import ReentrancyEvent
from .reentrancy.token import TokenReentrancy

from .shadowing.abstract import ShadowingAbstractDetection
from .shadowing.state import StateShadowing
from .shadowing.local import LocalShadowing
from .shadowing.builtin_symbols import BuiltinSymbolShadowing

from .slither.name_reused import NameReused

from .source.rtlo import RightToLeftOverride

from .statements.tx_origin import TxOrigin
from .statements.assembly import Assembly
from .statements.controlled_delegatecall import ControlledDelegateCall
from .statements.calls_in_loop import MultipleCallsInLoop
from .statements.incorrect_strict_equality import IncorrectStrictEquality
from .statements.deprecated_calls import DeprecatedStandards
from .statements.too_many_digits import TooManyDigits
from .statements.type_based_tautology import TypeBasedTautology
from .statements.boolean_constant_equality import BooleanEquality
from .statements.boolean_constant_misuse import BooleanConstantMisuse
from .statements.divide_before_multiply import DivideBeforeMultiply
from .statements.unprotected_upgradeable import UnprotectedUpgradeable
from .statements.mapping_deletion import MappingDeletionDetection
from .statements.array_length_assignment import ArrayLengthAssignment
from .statements.redundant_statements import RedundantStatements
from .statements.costly_operations_in_loop import CostlyOperationsInLoop
from .statements.assert_state_change import AssertStateChange
from .statements.unary import IncorrectUnaryExpressionDetection
from .statements.write_after_write import WriteAfterWrite
from .statements.msg_value_in_loop import MsgValueInLoop
from .statements.delegatecall_in_loop import DelegatecallInLoop

from .variables.uninitialized_state_variables import UninitializedStateVarsDetection
from .variables.uninitialized_storage_variables import UninitializedStorageVars
from .variables.uninitialized_local_variables import UninitializedLocalVars
from .variables.var_read_using_this import VarReadUsingThis
from .variables.unused_state_variables import UnusedStateVars
from .variables.could_be_constant import CouldBeConstant
from .variables.could_be_immutable import CouldBeImmutable
from .variables.similar_variables import SimilarVarsDetection
from .variables.function_init_state_variables import FunctionInitializedState
from .variables.predeclaration_usage_local import PredeclarationUsageLocal
from .variables.unchanged_state_variables import UnchangedStateVariables

from .customized_rules.dream import Dream
